// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gelman_rubin_cpp
double gelman_rubin_cpp(List chains);
RcppExport SEXP _MCMCDiag_gelman_rubin_cpp(SEXP chainsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type chains(chainsSEXP);
    rcpp_result_gen = Rcpp::wrap(gelman_rubin_cpp(chains));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MCMCDiag_gelman_rubin_cpp", (DL_FUNC) &_MCMCDiag_gelman_rubin_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_MCMCDiag(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
