# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gelman_rubin_cpp <- function(chains) {
    .Call(`_MCMCDiag_gelman_rubin_cpp`, chains)
}

